version: '3'

services:
  pypi-server:
    image: yen3/pypi-server:1.3.0
    restart: always
    command: ["-v", "-P", "/data/htpasswd.txt", "--overwrite"]
    volumes:
      - ./packages:/data/packages
      - ./htpasswd.txt:/data/htpasswd.txt
    ports:
      - "10080:8080"
